filebeat.inputs:
  - type: log
    paths:
      - /cowrie_logs/cowrie.json  # Corrected path to Cowrie logs
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    paths:
      - /dionaea_logs/*.log
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    paths:
      - /glastopf_logs/*.log
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["elk:5044"]

setup.kibana:
  host: "elk:5601"

processors:
  - add_docker_metadata: ~
